#include <msp430.h>
#include "buzzer.h"
#include "warsBuzz.h"
#include "buttons.h"

static int starWars[] ={a4,r,a4,r,a4,r,f4,r,c5, r,  a4, r,  f4, r, c5, r, a4,a4,a4, r,  e5, r,  e5, r,  e5, r,  f5, r, c5, r,  g5, r,  f5, r,  c5, r, a4,a4,a4,a4,a4, r,r,r,r,r,r,r,r};                  //Song 1
static int random[]= {  f4,  f4, f4,  a4s, r,  f5,  d5s,  d5,  c5, a5s,a5s, f5,r, d5s,  d5,  c5, a5s,a5s, f5, d5s, d5,d5s, c5,c5,c5,c5,r,r,r,r,r,r,r,r};                  
static int scale[] ={c,cH,d,eb,e,f,fH,g,ab,a,bb,b,c5};                    
static int eternity[] ={g4, r, c5, r, d5, r, d5s, f5, d5s, g4, r, g4, r, c5, d5, d5s, g4, d5s, c5, g5, f5, f5, f5, r, g4, r, c5, d5, d5s, g4, g5, d5s, g5s, g5s, r, c5, d5s, d5, c5, g5, d5s, c5, g4,g4,r};  
 
void notes(){            //method traversing thorugh each note of the array picked by the buttons
  static int currentNote=0;    //Sound generated by using the method buzzer_set_period in buzzer.c
  buzzer_set_period(0);
  if(play==1){
    if(currentNote < sizeof(starWars)){
      buzzer_set_period(starWars[currentNote++]);                     //Song 1
    }
    else{
      play=0;
      currentNote=0;
    }
  }
  
  if(play==2){
    if(currentNote < sizeof(random)){
      buzzer_set_period(random[currentNote++]);                       //Song 2
    }
    else{
      play=0;
      currentNote=0;
    }
  }

  if(play==3){
    if(currentNote < sizeof(scale)){
      buzzer_set_period(scale[currentNote++]);                       //Song 3
    }
    else{
      play=0;
      currentNote=0;
    }
  }

  if(play==4){
    if(currentNote < sizeof(eternity)){
      buzzer_set_period(eternity[currentNote++]);                     //Song 4
    }
    else{
      play=0;
      currentNote=0;
    }
  }
}

//LED code from demos unchanged
char toggle_red(){/* always toggle! */

  static char state = 0;
  switch (state) {
  case 0:
    red_on = 1;
    state = 1;
    break;
  case 1:
    red_on = 0;
    state = 0;
    break;
  }
  return 1;/* always changes an led */
}

char toggle_green(){   /* only toggle green if red is on!  */
  char changed = 0;
  if (red_on) {
    green_on ^= 1;
    changed = 1;
  }
  return changed;
}

void state_advance(){/* alternate between toggling red & green */
  char changed = 0;
  static enum {R=0, G1=1} color = G1;
  switch (color) {
  case R: changed = toggle_red(); color = G1; break;
  case G1: changed = toggle_green(); color = R; break;
  }
  led_changed = changed;
  led_update();
}
